<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Ast\Declaration\" />
      <Folder Include="Ast\Statement\" />
      <Folder Include="CodeGenerator\" />
      <Folder Include="Syntax\" />
    </ItemGroup>

</Project>
